### ISSUE TITLE
Please output "extension present" additionally to "file not found"

### ISSUE THREAD

**Issue by koppor** [u-fischer/newpax#1]
As user I get following error message

    ..ata/Local/Programs/MiKTeX/tex/lualatex/newpax/newpax.lua:428: file not found

I think, something is wrong with the `.lua`. However, it was just because I had

    \includegraphics[scale=0.8]{node_p2.pdf}

instead of

    \includegraphics[scale=0.8]{node_p2}

Maybe, the error message could be better: "Check if ...filename... is present"

**Comment by u-fischer** [comment]
Sorry I can't reproduce this error. It doesn't matter if one use `\includegraphics[scale=0.5]{node_p2.pdf}` or `\includegraphics[scale=0.5]{node_p2}`.  Please always make a complete example.

**Comment by u-fischer** [comment]
you meant `newpax.writenewpax`, not `\includegraphics`, and I have improved the message.

**Comment by koppor** [comment]
I think, I was just adding the extension to `writenewpax`

```tex
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
\documentclass{article}
\directlua{require("newpax")}
\directlua
{
newpax.writenewpax("doc-input1.pdf")
}

\usepackage{pdfpages,xcolor}
\usepackage{hyperref}
\hypersetup{linkbordercolor=blue}
\usepackage{newpax}

\begin{document}
\includegraphics[scale=0.5,trim=4cm 15cm 8cm 3cm,clip,page=1]{doc-input1.pdf}
\end{document}
```

Output

```
ta/Local/Programs/MiKTeX/tex/lualatex/newpax/newpax.lua:428: file doc-input1.pd
f not found
stack traceback:
        [C]: in function 'assert'
        ...ata/Local/Programs/MiKTeX/tex/lualatex/newpax/newpax.lua:428: in upvalue '_
_writepax'
        ...ata/Local/Programs/MiKTeX/tex/lualatex/newpax/newpax.lua:511: in function '
newpax.writenewpax'
        [\directlua]:1: in main chunk.
l.8 }

?
! Emergency stop.
l.8 }
```

If I remove the extension, then it works (as also outlined in the documentation). However, I would really like if I could also use the filename `doc-input1.pdf` instead of the filename without extension at `newpax.writenewpax`.

**Comment by u-fischer** [comment]
> However, I would really like if I could also use the filename doc-input1.pdf 

I didn't want to add some complicated lookup system (and didn't want to have to decide which file `a.pdf` should use, if both `a.pdf` and `a.pdf.pdf`  exist on a system), and leaving the extension out seems more useful to me, I seldom type .pdf.  

Beside this: the directlua should imho at the end be hidden in some latex command, and this could then strip off the pdf.
