### ISSUE TITLE
newpax fails on some MS-Word generated pdfs

### ISSUE THREAD

**Issue by vbeffara** [u-fischer/newpax#10]
Hello again,

On my system with uptodate `newpax`, I get a failure when I try to read the attached file
[toto.pdf](https://github.com/u-fischer/newpax/files/7611859/toto.pdf)

Error message:
```
newpax.lua:383: attempt to index a nil value (field '?')
stack traceback:
	./newpax.lua:383: in upvalue 'outputENTRY_dest'
	./newpax.lua:465: in upvalue '__writepax'
	./newpax.lua:507: in function 'newpax.writepax'
	[\directlua]:1: in main chunk.
```

This is when running the following `.tex` file with lualatex:
```
\documentclass{article}
\directlua{
    require("newpax")
    newpax.writepax("toto")
    newpax.writenewpax("toto")
}
\begin{document}
\end{document}
```

(It is not my pdf so I have no more information about its origin than the metadata - what I am attaching here is one page extracted using `pdftk` from a larger pdf that was itself created by MS Word and which provokes the same error. But I do not have the original `.doc` file.)

**Comment by CSchoel** [comment]
Same here for two of my journal papers (so I cannot say how they were generated and have no access to the intermediate files used by the journal):

[InaMo](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0254749&type=printable)
[HH-modelica](https://fjfsdata01prod.blob.core.windows.net/articles/files/583203/pubmed-zip/.versions/1/.package-entries/fphys-11-583203/fphys-11-583203.pdf?sv=2018-03-28&sr=b&sig=Oi80k5Nl1nXB7vygK%2B%2BUO03JuimodmRS%2BlBDj0UXYhE%3D&se=2022-03-24T15%3A34%3A09Z&sp=r&rscd=attachment%3B%20filename%2A%3DUTF-8%27%27fphys-11-583203.pdf)

The error is exactly the same except for the last line number.

```
/usr/share/texmf-dist/tex/latex/newpax/newpax.lua:383: attempt to index a nil value (field '?')
stack traceback:
	/usr/share/texmf-dist/tex/latex/newpax/newpax.lua:383: in upvalue 'outputENTRY_dest'
	/usr/share/texmf-dist/tex/latex/newpax/newpax.lua:465: in upvalue '__writepax'
	/usr/share/texmf-dist/tex/latex/newpax/newpax.lua:511: in function 'newpax.writenewpax'
	[\directlua]:1: in main chunk.
```

**Comment by u-fischer** [comment]
this should be resolved with the update.
