### ISSUE TITLE
Open issue againts pax

### ISSUE THREAD

**Issue by bastien-roucaries** [u-fischer/newpax#13]
Hi,

Could you open issue against pax ? 

I can help to get your functionnality merged BTW

**Comment by u-fischer** [comment]
sorry? An issue about what?

**Comment by u-fischer** [comment]
Sorry I don't have a list of the bugs I found in pax while writing newpax. I didn't assume that pax would be developed again. You will have to compare the code of the two sty to find out what I changed.
