### ISSUE TITLE
PDF files without metadata can't be processed

### ISSUE THREAD

**Issue by ublefo** [u-fischer/newpax#17]
Related to #15 but not quite the same error. This time the PDF doesn't seem to have any metadata so the script produces a different error now, even with cb9d43900d9452ed3a0e9114fe939c63d0281eae applied. Is the date doing anything useful here? Would it be a better idea to remove it entirely so the lua script won't have to deal with these unpredictable metadata?

Here's a test file to reproduce the error: [no_metadata.pdf](https://github.com/u-fischer/newpax/files/9541544/no_metadata.pdf)

```
Lua module: newpax 2022-06-27 0.52 newpax lua code/tmp/texlive/texmf-dist/tex/latex/newpax/newpax.lua:209: attempt to index a nil value
stack traceback:
        /tmp/texlive/texmf-dist/tex/latex/newpax/newpax.lua:209: in upvalue 'outputENTRY_file'
        /tmp/texlive/texmf-dist/tex/latex/newpax/newpax.lua:476: in upvalue '__writepax'
        /tmp/texlive/texmf-dist/tex/latex/newpax/newpax.lua:544: in function 'newpax.writenewpax'
        [\directlua]:1: in main chunk.l.35   }
```

**Comment by u-fischer** [comment]
Thanks, I uploaded a new version to ctan which fix this.

**Comment by ublefo** [comment]
Thanks for the quick fix, it works great now.
