### ISSUE TITLE
PDF files with a link generated on macOS can't be processed 

### ISSUE THREAD

**Issue by ublefo** [u-fischer/newpax#18]
Hello, it's me again with more edge cases. It seems like PDF files generated on macOS with Pages cannot be processed if they have hyperlinks at all. Rewriting this file with Ghostscript seems to be a valid workaround for now.

Here's a test file: [SamplePDF-link.pdf](https://github.com/u-fischer/newpax/files/9546768/SamplePDF-link.pdf)

```
Lua module: newpax 2022-06-27 0.52 newpax lua code/tmp/texlive/texmf-dist/tex/latex/newpax/newpax.lua:330: attempt to concatenate a luatex.pdfe.reference value (local 'value')
stack traceback:
        /tmp/texlive/texmf-dist/tex/latex/newpax/newpax.lua:330: in upvalue 'outputKV_uri'
        /tmp/texlive/texmf-dist/tex/latex/newpax/newpax.lua:513: in upvalue '__writepax'
        /tmp/texlive/texmf-dist/tex/latex/newpax/newpax.lua:544: in function 'newpax.writenewpax'
        [\directlua]:1: in main chunk.l.35   }
```

**Comment by u-fischer** [comment]
I pushed a change but before I send an update to ctan I should check if there are other places where indirect objects could lead to failures.

**Comment by ublefo** [comment]
Thanks once again for the quick fix, I'll test this in a bit and report back.
