### ISSUE TITLE
Add support for `#` in URLs

### ISSUE THREAD

**Issue by koppor** [u-fischer/newpax#3]
I have a `.newpax` file containing following:

```lua
\[{annot}{1}{Link}{290.694 332.028 426.701 369.717}{URI}{
  C={[1.0 1.0 1.0 ]},
  H={/I},
  Border={[0 0 1 ]},
  BS={<</S/S/Type/Border/W 1>>},
  URI={(https://docs.camunda.org/get-started/quick-start/service-task/#configure-the-service-task)},
}\\
```

lualatex then complains

```
(./camunda_p1.newpax) [104<./images/camunda.png>] (./camunda_p2.newpax
! Illegal parameter number in definition of \NEWPAX@key@URI.
<to be read again>
c
l.42 }
    \\
```

I think, `#` needs to be escape with `\` in `.newpax` files.

**Comment by koppor** [comment]
Think this was fixed in https://github.com/u-fischer/newpax/commit/bb0371a71af10daa6c4424fdacee59331a4c3b49; thus I am just waiting for new release to test it at https://github.com/gi-ev/LNI-proceedings to finally fix https://github.com/gi-ev/LNI-proceedings/issues/5.

**Comment by u-fischer** [comment]
I released today a new version, it *requires*  a new pdfmanagement-testphase version that I released today too.
