### ISSUE TITLE
"\includepdf[landscape=true" stops working

### ISSUE THREAD

**Issue by koppor** [u-fischer/newpax#4]
```
! Undefined control sequence.
\AM@setRotate ->\PLS@Rotate
                            {90}
l.20 ...paper=true,pages=-]{anhang/process_diva.pdf}
```

I will try to provide a MWE if necessary.

**Comment by u-fischer** [comment]
That is not a problem of newpax. pdfpages is here incompatible with the new PDF management as it uses an internal command of pdflscape which is no longer there.  I will close here an open an issue at the pdfresources github.

**Comment by koppor** [comment]
@u-fischer Thank you very much for providing the MWE at https://github.com/latex3/pdfresources/issues/15 🎉

**Comment by AndreasMatthias** [comment]
Pdfpages version 0.5t will fix this issue. I've just uploaded it to CTAN.
