### ISSUE TITLE
How to create a compressed PDF?

### ISSUE THREAD

**Issue by koppor** [u-fischer/newpax#8]
When using newpax, the resulting PDF seems to be uncompressed (even though it should be compressed - see https://github.com/latex3/pdfresources/issues/16#issuecomment-800996908)

I fixed it by following:

```latex
\RequirePackage{pdfmanagement-testphase}
%\DeclareDocumentMetadata{compress}
\documentclass{llncs}
\directlua{
  require("newpax")
  pdf.setcompresslevel(9)
  pdf.setminorversion(10)
}
```

Should that be added to the documentation?

(I also set the minor version to 10 as newpax seems to set it to 5 causing issues here)

Should I use [pdfsizeopt](https://github.com/pts/pdfsizeopt) as recommended by https://tex.stackexchange.com/a/215328/9075 to create a compressed PDF or is there another solution?

**Comment by u-fischer** [comment]
If you don't use `\DeclareDocumentMetadata{}`  I can't and won't garanty that newpax sty will work correctly. 

Also newpax doesn't set or change the compresslevel. But the examples use `\DeclareDocumentMetadata{uncompress}` as this is what I need for debugging. Simply remove the `uncompress` key if you don't need it. 

I have no idea how well pdfsizeopt works, and please don't missue the issue tracker here to get general pdf support. I have already enough to do.
